apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-site
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: my-image=ghcr.io/olavte99/testwebsite:latest
    argocd-image-updater.argoproj.io/my-image.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git


spec:
  project: default
  source:
    repoURL: https://github.com/olavte99/testwebsite.git
    targetRevision: main
    path: k8s
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: mock
  syncPolicy:
    automated:
      prune: true
      selfHeal: true