apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testwebsite
  namespace: argocd
  annotations:
# Track the web image and allow updates within 0.1.x
    argocd-image-updater.argoproj.io/image-list: web=ghcr.io/olavte99/testwebsite:latest


# Let Image Updater write the new tag back via Argo CD parameters (no Git write required)
    argocd-image-updater.argoproj.io/write-back-method: argocd


# (Optional) update strategy per-image, defaults to semver for this constraint
# argocd-image-updater.argoproj.io/web.update-strategy: semver
spec:
  project: default
  source:
    repoURL: https://github.com/olavte99/testwebsite.git
    targetRevision: HEAD
    path: k8s
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true