apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
data:
  registries.conf: |
    registries:
      - name: GHCR
        api_url: https://ghcr.io
        prefix: ghcr.io
        credentials: pullsecret:default/ghcr-creds-argo
        default: true

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-ghcr-secret
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["ghcr-creds-argo"]
    verbs: ["get"]