apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
data:
  registries.conf: |
    registries:
      - name: GHCR
        api_url: https://ghcr.io/olavte99/testwebsite
        prefix: ghcr.io/olavte99/testwebsite
        credentials: pullsecret:argocd/ghcr-cred-argo
        default: true