apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml


images:
  - name: ghcr.io/olavte99/testwebsite:latest
    newTag: 0.1.0 # <-- starting tag; Image Updater will bump this